# Generated by Django 3.2.8 on 2021-12-09 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clientmst',
            fields=[
                ('clientid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 9, 17, 2, 57, 682782), null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
