# Generated by Django 3.2.8 on 2021-12-10 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientmst',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 12, 32, 38, 988135), null=True),
        ),
    ]
