# Generated by Django 3.2.8 on 2021-12-10 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fatema', '0002_auto_20211210_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 15, 8, 35, 645964), null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 15, 8, 35, 645964), null=True),
        ),
        migrations.AlterField(
            model_name='clientmst',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 15, 8, 35, 645964), null=True),
        ),
    ]
